---
title: "density_plot"
author: "Luke Welsh"
date: "10/21/2023"
output: html_document
---

```{r}
library(reshape2) # For melt function
library(MASS)
library(sportyR)
library(gganimate)
library(ggplot2)
library(tidyverse)
```

```{r}
# Read in all pbp data ####
pbp <- read.csv("pbp.csv") %>% 
  mutate(event_goalie_name = str_replace_all(event_goalie_name, "\\.", " "),
         home_goalie = str_replace_all(home_goalie, "\\.", " "),
         away_goalie = str_replace_all(away_goalie, "\\.", " "),
         event_goalie_team = case_when(event_team == home_name ~ away_name,
                                       event_team == away_name ~ home_name))
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
# filter ev out of pbp data ####
real_strengths <- c(
    "5v5","5v4","5v3","6v5","6v4","6v3","4v3","3v3",
    "4v4","4v5","3v5","5v6","4v6","3v6","3v4"
  )

  fenwick <- c("SHOT","MISSED_SHOT","GOAL")
  
ev <- pbp %>%
    filter(period_type != "SHOOTOUT") %>% 
    filter(secondary_type != "Penalty Shot" | is.na(secondary_type)) %>% 
    group_by(game_id) %>% 
    mutate(
      last_event_type = lag(event_type),
      last_event_team = lag(event_team),
      time_since_last = game_seconds - lag(game_seconds),
      last_x_fixed = lag(x_fixed),
      last_y_fixed = lag(y_fixed),
      distance_from_last = round(sqrt(((y_fixed - last_y_fixed)^2) + ((x_fixed - last_x_fixed)^2)),1),
      event_zone = case_when(
        x >= -25 & x <= 25 ~ "NZ",
        (x_fixed < -25 & event_team == home_name) |
          (x_fixed > 25 & event_team == away_name) ~ "DZ",
        (x_fixed > 25 & event_team == home_name) |
          (x_fixed < -25 & event_team == away_name) ~ "OZ"
      ),
      last_event_zone = lag(event_zone)
    ) %>% 
    ungroup() %>%
    filter(strength_code == "EV") %>% #filter for even strength
    filter(strength_state %in% real_strengths) %>% #eliminating weird strengths
    filter(event_type %in% fenwick) %>%  # unblocked shots only
    # get rid off oddball last_events, ie "EARLY_INTERMISSION_START"
    filter(last_event_type %in% c("FACEOFF","GIVEAWAY","TAKEAWAY","BLOCKED_SHOT","HIT",
                                  "MISSED_SHOT","SHOT","STOP","PENALTY","GOAL")) %>% 
    # add more feature variables
    mutate(
      # these are only for the ST model
      event_team_skaters = ifelse(event_team == home_name, home_skaters, away_skaters),
      opponent_team_skaters = ifelse(event_team == home_name, away_skaters, home_skaters),
      total_skaters_on = event_team_skaters + opponent_team_skaters,
      # these are in 5v5 model
      # if last event was shot within 2 seconds rebound == 1
      rebound = ifelse(last_event_type %in% fenwick & time_since_last <= 2, 1, 0),
      rush = ifelse(last_event_zone %in% c("NZ","DZ") & time_since_last <= 4, 1, 0),
      
      cross_ice_event = ifelse(
        # indicates goalie had to move from one post to the other
        last_event_zone == "OZ" &
          ((lag(y) >  3 & y < -3) | (lag(y) < -3 & y > 3)) &
          # need some sort of time frame here to indicate shot was quick after goalie had to move
          time_since_last <= 2, 1, 0
      ),
      takeaway = ifelse(last_event_zone == "OZ" & last_event_type == "TAKEAWAY" & time_since_last <= 2, 1, 0),
      giveaway = ifelse(last_event_zone == "OZ" & last_event_type == "GIVEAWAY" & time_since_last <= 2, 1, 0),
      forecheck = ifelse(last_event_zone == "OZ" & last_event_type %in% c("TAKEAWAY", "GIVEAWAY") & time_since_last <= 2, 1, 0),
      empty_net = ifelse(is.na(empty_net) | empty_net == FALSE, FALSE, TRUE),
      shot_type = secondary_type,
      goal = ifelse(event_type == "GOAL", 1, 0), 
      goal_x = case_when(
        event_team == home_name ~ 89,
        event_team == away_name ~ -89
      ),
      reb_dist = sqrt((goal_x-x_fixed)**2 + y_fixed**2), 
      first_dist = sqrt((goal_x-last_x_fixed)**2 + last_y_fixed**2),
      betw_shot_dist = sqrt((last_x_fixed-x_fixed)**2 + (last_y_fixed-y_fixed)**2),
      angle_change = acos((first_dist**2+reb_dist**2-betw_shot_dist**2)/(2*first_dist*reb_dist)) * (180 / pi)
    )

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# filter pp out of pbp data ####
pp <- pbp %>% 
  select(-xg) %>% 
    filter(period_type != "SHOOTOUT") %>% 
    filter(secondary_type != "Penalty Shot" | is.na(secondary_type)) %>% 
    group_by(game_id) %>% 
    mutate(
      last_event_type = lag(event_type),
      last_event_team = lag(event_team),
      time_since_last = game_seconds - lag(game_seconds),
      last_x_fixed = lag(x_fixed),
      last_y_fixed = lag(y_fixed),
      distance_from_last = round(sqrt(((y_fixed - last_y_fixed)^2) + ((x_fixed - last_x_fixed)^2)),1),
      event_zone = case_when(
        x >= -25 & x <= 25 ~ "NZ",
        (x_fixed < -25 & event_team == home_name) |
          (x_fixed > 25 & event_team == away_name) ~ "DZ",
        (x_fixed > 25 & event_team == home_name) |
          (x_fixed < -25 & event_team == away_name) ~ "OZ"
      ),
      last_event_zone = lag(event_zone)
    ) %>% 
    ungroup() %>%
    filter(strength_code == "PP") %>% #filter for even strength
    filter(strength_state %in% real_strengths) %>% #eliminating weird strengths
    filter(event_type %in% fenwick) %>%  # unblocked shots only
    # get rid off oddball last_events, ie "EARLY_INTERMISSION_START"
    filter(last_event_type %in% c("FACEOFF","GIVEAWAY","TAKEAWAY","BLOCKED_SHOT","HIT",
                                  "MISSED_SHOT","SHOT","STOP","PENALTY","GOAL")) %>% 
    # add more feature variables
    mutate(
      # these are only for the ST model
      event_team_skaters = ifelse(event_team == home_name, home_skaters, away_skaters),
      opponent_team_skaters = ifelse(event_team == home_name, away_skaters, home_skaters),
      total_skaters_on = event_team_skaters + opponent_team_skaters,
      # these are in 5v5 model
      # if last event was shot within 2 seconds rebound == 1
      rebound = ifelse(last_event_type %in% fenwick & time_since_last <= 2, 1, 0),
      rush = ifelse(last_event_zone %in% c("NZ","DZ") & time_since_last <= 4, 1, 0),
      
      cross_ice_event = ifelse(
        # indicates goalie had to move from one post to the other
        last_event_zone == "OZ" &
          ((lag(y) >  3 & y < -3) | (lag(y) < -3 & y > 3)) &
          # need some sort of time frame here to indicate shot was quick after goalie had to move
          time_since_last <= 2, 1, 0
      ),
      empty_net = ifelse(is.na(empty_net) | empty_net == FALSE, FALSE, TRUE),
      shot_type = secondary_type,
      goal = ifelse(event_type == "GOAL", 1, 0), 
      goal_x = case_when(
        event_team == home_name ~ 89,
        event_team == away_name ~ -89
      ),
      reb_dist = sqrt((goal_x-x_fixed)**2 + y_fixed**2), 
      first_dist = sqrt((goal_x-last_x_fixed)**2 + last_y_fixed**2),
      betw_shot_dist = sqrt((last_x_fixed-x_fixed)**2 + (last_y_fixed-y_fixed)**2),
      angle_change = acos((first_dist**2+reb_dist**2-betw_shot_dist**2)/(2*first_dist*reb_dist)) * (180 / pi)
    ) 
```

```{r}

# Courtesy of Stats with Matt: https://github.com/mtthwastn/statswithmatt/tree/master/hockey-with-r

gg_rink <- function(nsteps, side = "right", specs = "nhl"){
  
  ### this function uses ggplot's annotate()
  # to draw the rink.
  # I recommend calling this function PRIOR to invoking
  # geoms for data so that the points aren't covered
  # by the annotations
  
  ### inputs:
  #     1. side = which side to plot: "right" (default) or "left"
  #     2. specs = which rink size to use: "nhl" (default) or "iihf" for
  #        international
  
  # check inputs
  side <- tolower(side)
  specs <- tolower(specs)
  stopifnot(side %in% c("right", "left"))
  stopifnot(specs %in% c("nhl", "iihf"))
  
  side <- switch(side,
                 "right" = 1,
                 "left" = -1)
  
  nsteps <- nsteps # line resolution for drawing circles/segments
  circle <- seq(0, 2*pi, length = nsteps) # angles to draw a circle
  
  switch(specs,
         "nhl" = {
           # NHL specifications
           # all units in feet
           
           ### rink boundaries ###
           ## assumed to be standard 200x85ft dimensions
           x_max <- 100
           y_max <- 42.5
           y_min <- -y_max
           # blue line 75' from end boards
           x_blue <- x_max - 75
           # goal line 11' from end boards
           x_goal <- x_max - 11
           
           ### parameter setup
           ## corners rounded in arc of circle with 28' radius
           r_corner <- 28
           
           ## crease semi-circle
           # 6' radius from center of goal line starting 4.5' out
           crease_end <- 4.5
           r_crease <- 6
           # deepest point of net is 40"
           net_depth <- 40/12
           # crease is 8' long; goal posts 6' apart
           goal_post_start <- 6/2
           crease_start_y <- 8/2
           # inner crease lines begin 4' from goal line
           # extend 5" into crease
           crease_small_start <- 4
           crease_small_length <- 5/12
           
           ## face-off circle dots and lines
           # dot locations: 20' from goal line, 22' in each y direction
           x_dot_dist <- 20
           y_faceoff_dot <- 22
           # face-off circle radius 15'
           r_faceoff <- 15
           # hash marks 2' long, 5'7" apart
           hash_length <- 2
           hash_space <- 67/12
           # circle inner lines:
           # x-direction: lines 4' apart, so start 2' from dot
           # y-direction: lines 18" apart, so start 9" from dot
           inner_start_x <- 2
           inner_start_y <- 1.5/2
           # lines parallel to side boards: 4' long
           par_side_length <- 4
           # lines parallel to end boards: 3' long
           par_end_length <- 3
           
           ## other parameters
           # neutral zone dots are 5' from blue line, 44' apart
           x_dot_neutral <- 5
           # ref circle 5m radius
           r_ref <- 5
           ## trapezoid (NHL only)
           # begins 8' from each goal post
           # bottom base is 28' long
           y_traps_start <- goal_post_start + 8
           y_traps_end <- 14
         },
         "iihf" = {
           # IIHF specifications
           # all units in meters
           
           ### rink boundaries ###
           ## assumed to be standard 60x30m dimensions
           x_max <- 30
           y_max <- 15
           y_min <- -y_max
           # blue line 22.86m from end boards, 30cm wide
           x_blue <- x_max - 22.86
           # goal line 4m from end boards
           x_goal <- x_max - 4
           
           ### parameter setup
           ## corners rounded in arc of circle with 8.5m radius
           r_corner <- 8.5
           
           ## crease semi-circle
           # 183cm radius from center of goal line starting 137cm out
           crease_end <- 1.37
           r_crease <- 1.83
           # deepest point of net is 1.12m
           net_depth <- 1.12
           # crease is 244cm long; goal posts 183.5cm apart
           goal_post_start <- 1.835/2
           crease_start_y <- 2.44/2
           # inner crease lines begin 122cm from goal line
           # extend 13m into crease
           crease_small_start <- 1.22
           crease_small_length <- 0.13
           
           ## face-off circle dots and lines
           # dot locations: 6m from goal line, 7m in each y direction
           x_dot_dist <- 6
           y_faceoff_dot <- 7
           # face-off circle radius 4.5m
           r_faceoff <- 4.5
           # hash marks 60cm long, 170cm apart
           hash_length <- 0.6
           hash_space <- 1.7
           # circle inner lines:
           # x-direction: lines 120cm apart, start 60cm from dot
           # y-direction: lines 45cm apart, so start 22.5cm from dot
           inner_start_x <- 0.6
           inner_start_y <- 0.225
           # lines parallel to side boards: 120cm long
           par_side_length <- 1.2
           # lines parallel to end boards: 90cm long
           par_end_length <- 0.9
           
           ## other parameters
           # neutral zone dots are 1.5m from blue line
           x_dot_neutral <- 1.5
           # ref circle 3m radius
           r_ref <- 3
         }
  )
  
  ## corners
  curve_angle <- seq(pi/2, 0, length = nsteps)
  curve_angle_last <- curve_angle[nsteps]
  # y coord at end of curve to connect ends
  y_curve_end <- (y_max - r_corner) + r_corner*sin(curve_angle_last)
  # for goal line, find y coord when x is at goal line
  goal_angle <- acos(
    (x_goal - (x_max - r_corner))/r_corner
  )
  y_goal <- (y_max - r_corner) + r_corner*sin(goal_angle)
  
  ## crease
  crease_angles <- seq(
    pi - acos(crease_end/r_crease),
    pi + acos(crease_end/r_crease),
    length = nsteps
  )
  
  ## face-off circle
  x_faceoff_dot <- x_goal - x_dot_dist
  # find y coord on circle where hashes begin
  y_hash <- r_faceoff*sin(
    acos((hash_space/2)/r_faceoff)
  )
  
  ### create list of components to pass to ggplot
  list(
    theme_minimal(),
    theme(panel.grid = element_blank()),
    ### blue line
    annotate(
      "segment",
      x = x_blue*side, y = y_max,
      xend = x_blue*side, yend = y_min,
      color = "blue", size = 2
    ),
    ### ref crease
    annotate(
      "path",
      x = r_ref*cos(seq(pi/2, 0, length = nsteps))*side,
      y = y_min + r_ref*sin(seq(pi/2, 0, length = nsteps)),
      color = "red"
    ),
    ### face-off circle, center ice
    annotate(
      "path",
      x = r_faceoff*cos(seq(pi/2, -pi/2, length = nsteps))*side,
      y = r_faceoff*sin(seq(pi/2, -pi/2, length = nsteps)),
      color = "blue"
    ),
    ### center line:
    annotate(
      "segment",
      x = 0, y = y_max,
      xend = 0, yend = y_min,
      color = "red", size = 2
    ),
    switch(specs,
           "nhl" = annotate(
             # dashed white lines atop center line (NHL only)
             "segment",
             x = 0, y = y_max,
             xend = 0, yend = y_min,
             color = "white", size = 0.5, linetype = "dashed"
           ),
           "iihf" = annotate(
             # 50cm space between lines around center dot
             "segment",
             x = 0, y = 0.5,
             xend = 0, yend = -0.5,
             color = "white", size = 2.5
           )
    ),
    ### face-off dot, center ice
    annotate(
      "point",
      x = 0,
      y = 0,
      color = "blue", size = 1
    ),
    ### neutral zone dots
    annotate(
      "point",
      x = (x_blue - x_dot_neutral)*side,
      y = y_faceoff_dot*c(1, -1),
      color = "red", size = 1
    ),
    ### side boards
    annotate(
      "segment",
      x = 0, y = c(y_min, y_max),
      # stop where corner curve begins
      xend = (x_max - r_corner)*side, yend = c(y_min, y_max),
      size = 1
    ),
    ### ends
    # goal line
    annotate(
      "segment",
      x = x_goal*side, y = y_goal,
      xend = x_goal*side, yend = -y_goal,
      color = "red"
    ),
    # connect ends
    annotate(
      "segment",
      x = x_max*side, y = y_curve_end,
      xend = x_max*side, yend = -y_curve_end,
      size = 1
    ),
    # corners rounded in arc of circle
    # starting point: (x_max, y_max) - r_circle from pi/2 to 0
    annotate(
      "path",
      x = ((x_max - r_corner) + r_corner*cos(curve_angle))*side,
      y = (y_max - r_corner) + r_corner*sin(curve_angle),
      size = 1
    ),
    annotate(
      "path",
      x = ((x_max - r_corner) + r_corner*cos(curve_angle))*side,
      y = -((y_max - r_corner) + r_corner*sin(curve_angle)),
      size = 1
    ),
    ### crease
    annotate(
      "segment",
      x = x_goal*side,
      y = crease_start_y*c(-1, 1),
      xend = (x_goal - crease_end)*side,
      yend = crease_start_y*c(-1, 1),
      col = "red"
    ),
    # crease lines
    annotate(
      "segment",
      x = (x_goal - crease_small_start)*side,
      y = crease_start_y*c(-1, 1),
      xend = (x_goal - crease_small_start)*side,
      yend = (crease_start_y - crease_small_length)*c(-1, 1),
      col = "red"
    ),
    # semi-circle starting 137cm out with 183cm radius from center of goal line
    annotate(
      "path",
      x = (x_goal + r_crease*cos(crease_angles))*side,
      y = r_crease*sin(crease_angles),
      col = "red"
    ),
    if (specs == "nhl") {
      ### restricted area (NHL only)
      annotate(
        "segment",
        x = x_goal*side, y = y_traps_start*c(-1, 1),
        xend = x_max*side, yend = y_traps_end*c(-1, 1),
        color = "red"
      )
    },
    ### net
    annotate(
      "segment",
      x = x_goal*side,
      y = goal_post_start*c(-1, 1),
      xend = (x_goal + net_depth)*side,
      yend = goal_post_start*c(-1, 1)
    ),
    annotate(
      "segment",
      x = (x_goal + net_depth)*side,
      y = -goal_post_start,
      xend = (x_goal + net_depth)*side,
      yend = goal_post_start
    ),
    ### face-off circles
    # dot
    annotate(
      "point",
      x = x_faceoff_dot*side,
      y = y_faceoff_dot*c(1, -1),
      col = "red",
      size = 1
    ),
    # circles 
    annotate(
      # top
      "path",
      x = side*(x_faceoff_dot + r_faceoff*cos(circle)),
      y = y_faceoff_dot + r_faceoff*sin(circle),
      col = "red"
    ),
    annotate(
      # bottom
      "path",
      x = side*(x_faceoff_dot + r_faceoff*cos(circle)),
      y = -(y_faceoff_dot + r_faceoff*sin(circle)),
      col = "red"
    ),
    # hashes
    annotate(
      "segment",
      x = side*(
        x_faceoff_dot + (hash_space/2)*rep(c(1, -1), each = 4)
      ),
      y = (y_faceoff_dot + y_hash*c(1, -1))*rep(c(1, 1, -1, -1), times = 2),
      xend = side*(
        x_faceoff_dot + (hash_space/2)*rep(c(1, -1), each = 4)
      ),
      yend = (y_faceoff_dot + (y_hash + hash_length)*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      col = "red"
    ),
    ## inner lines
    # parallel to side boards
    annotate(
      # parallel to side boards
      "segment",
      x = side*(
        x_faceoff_dot + inner_start_x*rep(c(1, -1), each = 4)
      ),
      y = (y_faceoff_dot + inner_start_y*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      xend = side*(
        x_faceoff_dot + (inner_start_x + par_side_length)*
          rep(c(1, -1), each = 4)
      ),
      yend = (y_faceoff_dot + inner_start_y*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      col = "red"
    ),
    annotate(
      # parallel to end boards
      "segment",
      x = side*(
        x_faceoff_dot + inner_start_x*rep(c(1, -1), each = 4)
      ),
      y = (y_faceoff_dot + inner_start_y*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      xend = side*(
        x_faceoff_dot + inner_start_x*rep(c(1, -1), each = 4)
      ),
      yend = (y_faceoff_dot + (inner_start_y + par_end_length)*c(1, -1))*
        rep(c(1, 1, -1, -1), times = 2),
      col = "red"
    )
  )
}
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
shots23 <- ev %>%
  filter(season == 2023, !is.na(x), !is.na(y)) %>%
  mutate(x = abs(x))
shots16 <- ev %>%
  filter(season == 2016, !is.na(x), !is.na(y)) %>%
  mutate(x = abs(x))

xrng = range(c(shots23$x, shots16$x))
yrng = range(c(shots23$y, shots16$y))
d23 = kde2d(shots23$x, shots23$y, lims=c(xrng, yrng), n=200)
d16 = kde2d(shots16$x, shots16$y, lims=c(xrng, yrng), n=200)
diff = d23
diff$z = d23$z - d16$z
rownames(diff$z) = diff$x
colnames(diff$z) = diff$y

# Now melt it to long format
diff.m = melt(diff$z, id.var=rownames(diff))
names(diff.m) = c("X","Y","z")

ggplot() + 
  geom_tile(data = diff.m, mapping = aes(X, Y, z=z, fill=z)) +
  scale_fill_gradient2(high="#FFB81C", low = "#003087", midpoint=0) + 
  labs(fill = "Change in Frequency from 2016 to 2023") + 
  gg_rink(nsteps=100001) + 
  coord_equal() + 
  theme(legend.position = "none", 
        axis.title = element_blank(),
        axis.text = element_blank())
```





```{r}
years <- c("2017", "2018", "2019", "2020", "2021", "2022", "2023")

diffs <- data.frame()
graphs <- list()

shots16 <- ev %>% 
  filter(season == 2016, !is.na(x), !is.na(y)) %>% 
  mutate(x = abs(x))
d16 = kde2d(shots16$x, shots16$y, lims=c(xrng, yrng), n=200)

for (season_comp in years) {
  shots_season <- ev %>% 
    filter(season == season_comp, !is.na(x), !is.na(y)) %>% 
    mutate(x = abs(x))
  
  xrng = range(c(shots_season$x, shots16$x))
  yrng = range(c(shots_season$y, shots16$y))
  # 
  # # Calculate the 2d density estimate over the common range
  dens_season = kde2d(shots_season$x, shots_season$y, lims=c(xrng, yrng), n=200)
  # 
  # # Calculate the difference between the 2d density estimates
  diff = dens_season
  diff$z = dens_season$z - d16$z
  # 
  # ## Melt data into long format
  # # First, add row and column names (x and y grid values) to the z-value matrix
  rownames(diff$z) = diff$x
  colnames(diff$z) = diff$y
  diff.m = melt(diff$z, id.var=rownames(diff))
  names(diff.m) = c("X","Y","z")
  
  diff.m$year = season_comp
  diffs <- rbind(diffs, diff.m)
  
  g <- diff.m %>% 
    ggplot() + 
    geom_tile(mapping = aes(X, Y, fill=z)) +
    scale_fill_gradient2(high="#FFB81C", low = "#003087", midpoint=0) + 
    labs(title = paste("Difference in Shot Frequency from 2016 to", season_comp)) + 
    gg_rink(nsteps=100001) +
    coord_equal() + 
    theme(legend.position = "none", 
          axis.title = element_blank(),
          axis.text = element_blank())
  graphs[[season_comp]] <- g
}
```

```{r}
library(animation)
ani.options(interval = 1, ani.res = 100)
saveGIF({
  for (season_comp in years){
    print(graphs[[season_comp]])
  }
}, movie.name = "ex.gif")
```

```{r}
diff.m %>% 
    ggplot() + 
    geom_tile(mapping = aes(X, Y, fill=z)) +
    scale_fill_gradient2(high="#FFB81C", low = "#003087", midpoint=0) + 
    labs(title = paste("Difference in Shot Frequency from 2016 to", season_comp)) + 
    gg_rink(100001) +
    coord_equal() + 
    theme(legend.position = "none", 
          axis.title = element_blank(),
          axis.text = element_blank())
  graphs[[season_comp]] <- g
```







